[workspace]
resolver = "3"
members = ["crates/core", "crates/app"]

[workspace.package]
version = "1.4.0"
edition = "2024"
rust-version = "1.89"
license = "MIT"
repository = "https://github.com/akshit-bansal11/deskbeat"

[workspace.dependencies]
deskbeat-core = { path = "crates/core" }
rustfft = "6.4.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.6"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
opt-level = "s"
